ESXShared = ESXShared or {}
ESXShared.Vehicles = ESXShared.Vehicles or {}
ESXShared.VehiclesHash = ESXShared.VehiclesHash or {}

local Vehicles = {
    --- Compacts (0)
    { model = 'asbo', name = 'Asbo', brand = 'Maxwell', price = 4000, category = 'compacts'},
    { model = 'blista',          name = 'Blista',                        brand = 'Dinka',           price = 40000,   category = 'compacts'},
    { model = 'brioso',          name = 'Brioso R/A',                    brand = 'Grotti',          price = 70000,   category = 'compacts'},
    { model = 'club',            name = 'Club',                          brand = 'BF',              price = 60000,    category = 'compacts'},
    { model = 'dilettante',      name = 'Dilettante',                    brand = 'Karin',           price = 40000,    category = 'compacts'},
    { model = 'kanjo',           name = 'Blista Kanjo',                  brand = 'Dinka',           price = 50000,   category = 'compacts'},
    { model = 'issi2',           name = 'Issi',                          brand = 'Weeny',           price = 7000,    category = 'compacts'},
    { model = 'issi3',           name = 'Issi Classic',                  brand = 'Weeny',           price = 80000,    category = 'compacts'},
    { model = 'issi4',           name = 'Issi Arena',                    brand = 'Weeny',           price = 80000,   category = 'compacts'},
    { model = 'issi5',           name = 'Issi Future Shock',             brand = 'Weeny',           price = 80000,   category = 'compacts'},
    { model = 'issi6',           name = 'Issi Nightmare',                brand = 'Weeny',           price = 80000,   category = 'compacts'},
    { model = 'panto',           name = 'Panto',                         brand = 'Benefactor',      price = 32000,    category = 'compacts'},
    { model = 'prairie',         name = 'Prairie',                       brand = 'Bollokan',        price = 30000,   category = 'compacts'},
    { model = 'rhapsody',        name = 'Rhapsody',                      brand = 'Declasse',        price = 10000,   category = 'compacts'},
    { model = 'brioso2',         name = 'Brioso 300',                    brand = 'Grotti',          price = 12000,   category = 'compacts'},
    { model = 'weevil',          name = 'Weevil',                        brand = 'BF',              price = 100000,    category = 'compacts'},
    { model = 'issi7',           name = 'Issi Sport',                    brand = 'Weeny',           price = 100000,  category = 'compacts'},
    { model = 'blista2',         name = 'Blista Compact',                brand = 'Dinka',           price = 35000,   category = 'compacts'},
    { model = 'blista3',         name = 'Blista Go Go Monkey',           brand = 'Dinka',           price = 100000,   category = 'compacts'},
    { model = 'brioso3',         name = 'Brioso 300 Widebody',           brand = 'Grotti',          price = 125000,  category = 'compacts'},
    { model = 'boor',            name = 'Boor',                          brand = 'Karin',           price = 70000,   category = 'compacts'},
    --- Sedans (1)
    { model = 'asea',            name = 'Asea',                          brand = 'Declasse',        price = 100000,    category = 'sedans'},
    { model = 'asterope',        name = 'Asterope',                      brand = 'Karin',           price = 110000,   category = 'sedans'},
    { model = 'cog55',           name = 'Cognoscenti 55',                brand = 'Enus',            price = 450000,   category = 'sedans'},
    { model = 'cognoscenti',     name = 'Cognoscenti',                   brand = 'Enus',            price = 430000,   category = 'sedans'},
    { model = 'emperor',         name = 'Emperor',                       brand = 'Albany',          price = 100000,    category = 'sedans'},
    { model = 'fugitive',        name = 'Fugitive',                      brand = 'Cheval',          price = 100000,   category = 'sedans'},
    { model = 'glendale',        name = 'Glendale',                      brand = 'Benefactor',      price = 100000,    category = 'sedans'},
    { model = 'glendale2',       name = 'Glendale Custom',               brand = 'Benefactor',      price = 100000,   category = 'sedans'},
    { model = 'ingot',           name = 'Ingot',                         brand = 'Vulcar',          price = 100000,    category = 'sedans'},
    { model = 'intruder',        name = 'Intruder',                      brand = 'Karin',           price = 100000,   category = 'sedans'},
    { model = 'premier',         name = 'Premier',                       brand = 'Declasse',        price = 100000,   category = 'sedans'},
    { model = 'primo',           name = 'Primo',                         brand = 'Albany',          price = 100000,    category = 'sedans'},
    { model = 'primo2',          name = 'Primo Custom',                  brand = 'Albany',          price = 130000,   category = 'sedans'},
    { model = 'regina',          name = 'Regina',                        brand = 'Dundreary',       price = 100000,    category = 'sedans'},
    { model = 'stafford',        name = 'Stafford',                      brand = 'Enus',            price = 100000,   category = 'sedans'},
    { model = 'stanier',         name = 'Stanier',                       brand = 'Vapid',           price = 100000,   category = 'sedans'},
    { model = 'stratum',         name = 'Stratum',                       brand = 'Zirconium',       price = 100000,   category = 'sedans'},
    { model = 'stretch',         name = 'Stretch',                       brand = 'Dundreary',       price = 100000,   category = 'sedans'},
    { model = 'superd',          name = 'Super Diamond',                 brand = 'Enus',            price = 100000,   category = 'sedans'},
    { model = 'surge',           name = 'Surge',                         brand = 'Cheval',          price = 100000,   category = 'sedans'},
    { model = 'tailgater',       name = 'Tailgater',                     brand = 'Obey',            price = 100000,   category = 'sedans'},
    { model = 'warrener',        name = 'Warrener',                      brand = 'Vulcar',          price = 100000,    category = 'sedans'},
    { model = 'washington',      name = 'Washington',                    brand = 'Albany',          price = 100000,    category = 'sedans'},
    { model = 'tailgater2',      name = 'Tailgater S',                   brand = 'Obey',            price = 100000,   category = 'sedans'},
    { model = 'cinquemila',      name = 'Lampadati',                     brand = 'Cinquemila',      price = 125000,  category = 'sedans'},
    { model = 'iwagen',          name = 'Obey',                          brand = 'I-Wagen',         price = 225000,  category = 'sedans'},
    { model = 'astron',          name = 'Astron',                        brand = 'Pfister',         price = 150000,  category = 'sedans'},
    { model = 'baller7',         name = 'Baller ST',                     brand = 'Gallivanter',     price = 145000,  category = 'sedans'},
    { model = 'comet7',          name = 'Comet',                         brand = 'S2 Cabrio',       price = 100000,   category = 'sedans'},
    { model = 'deity',           name = 'Deity',                         brand = 'Enus',            price = 505000,  category = 'sedans'},
    { model = 'jubilee',         name = 'Jubilee',                       brand = 'Enus',            price = 485000,  category = 'sedans'},
    { model = 'oracle',          name = 'Oracle',                        brand = 'Übermacht',       price = 100000,   category = 'sedans'},
    { model = 'schafter2',       name = 'Schafter',                      brand = 'Benefactor',      price = 100000,   category = 'sedans'},
    { model = 'warrener2',       name = 'Warrener HKR',                  brand = 'Vulcar',          price = 100000,   category = 'sedans'},
    { model = 'rhinehart',       name = 'Rhinehart',                     brand = 'Übermacht',       price = 105000,  category = 'sedans'},
    { model = 'eudora',          name = 'Eudora',                        brand = 'Willard',         price = 100000,   category = 'sedans'},
    { model = 'asterope2',       name = 'Asterope GZ',                   brand = 'Karin',           price = 459000,  category = 'sedans'},
    { model = 'impaler5',        name = 'Impaler SZ',                    brand = 'Declasse',        price = 768000,  category = 'sedans'},
    --- SUV (2)
    { model = 'baller',          name = 'Baller',                        brand = 'Gallivanter',     price = 250000,   category = 'suvs'},
    { model = 'baller2',         name = 'Baller II',                     brand = 'Gallivanter',     price = 550000,   category = 'suvs'},
    { model = 'baller3',         name = 'Baller LE',                     brand = 'Gallivanter',     price = 660000,   category = 'suvs'},
    { model = 'baller4',         name = 'Baller LE LWB',                 brand = 'Gallivanter',     price = 766000,   category = 'suvs'},
    { model = 'bjxl',            name = 'BeeJay XL',                     brand = 'Karin',           price = 550000,   category = 'suvs'},
    { model = 'cavalcade',       name = 'Cavalcade',                     brand = 'Albany',          price = 550000,   category = 'suvs'},
    { model = 'cavalcade2',      name = 'Cavalcade II',                  brand = 'Albany',          price = 550000,   category = 'suvs'},
    { model = 'contender',       name = 'Contender',                     brand = 'Vapid',           price = 550000,   category = 'suvs'},
    { model = 'dubsta',          name = 'Dubsta',                        brand = 'Benefactor',      price = 550000,   category = 'suvs'},
    { model = 'dubsta2',         name = 'Dubsta Luxury',                 brand = 'Benefactor',      price = 750000,   category = 'suvs'},
    { model = 'fq2',             name = 'FQ2',                           brand = 'Fathom',          price = 100000,   category = 'suvs'},
    { model = 'granger',         name = 'Granger',                       brand = 'Declasse',        price = 120000,   category = 'suvs'},
    { model = 'gresley',         name = 'Gresley',                       brand = 'Bravado',         price = 150000,   category = 'suvs'},
    { model = 'habanero',        name = 'Habanero',                      brand = 'Emperor',         price = 120000,   category = 'suvs'},
    { model = 'huntley',         name = 'Huntley S',                     brand = 'Enus',            price = 350000,   category = 'suvs'},
    { model = 'landstalker',     name = 'Landstalker',                   brand = 'Dundreary',       price = 450000,   category = 'suvs'},
    { model = 'landstalker2',    name = 'Landstalker XL',                brand = 'Dundreary',       price = 500000,   category = 'suvs'},
    { model = 'novak',           name = 'Novak',                         brand = 'Lampadati',       price = 100000,   category = 'suvs'},
    { model = 'patriot',         name = 'Patriot',                       brand = 'Mammoth',         price = 100000,   category = 'suvs'},
    { model = 'patriot2',        name = 'Patriot Stretch',               brand = 'Mammoth',         price = 100000,   category = 'suvs'},
    { model = 'radi',            name = 'Radius',                        brand = 'Vapid',           price = 100000,   category = 'suvs'},
    { model = 'rebla',           name = 'Rebla GTS',                     brand = 'Übermacht',       price = 100000,   category = 'suvs'},
    { model = 'rocoto',          name = 'Rocoto',                        brand = 'Obey',            price = 100000,   category = 'suvs'},
    { model = 'seminole',        name = 'Seminole',                      brand = 'Canis',           price = 100000,   category = 'suvs'},
    { model = 'seminole2',       name = 'Seminole Frontier',             brand = 'Canis',           price = 100000,   category = 'suvs'},
    { model = 'serrano',         name = 'Serrano',                       brand = 'Benefactor',      price = 100000,   category = 'suvs'},
    { model = 'toros',           name = 'Toros',                         brand = 'Pegassi',         price = 100000,   category = 'suvs'},
    { model = 'xls',             name = 'XLS',                           brand = 'Benefactor',      price = 100000,   category = 'suvs'},
    { model = 'granger2',        name = 'Granger 3600LX',                brand = 'Declasse',        price = 221000,  category = 'suvs'},
    { model = 'patriot3',        name = 'Patriot Military',              brand = 'Mil-Spec',        price = 270000,  category = 'suvs'},
    { model = 'aleutian',        name = 'Aleutian',                      brand = 'Vapid',           price = 183500,  category = 'suvs'},
    { model = 'baller8',         name = 'Baller ST-D',                   brand = 'Gallivanter',     price = 171500,  category = 'suvs'},
    { model = 'cavalcade3',      name = 'Cavalcade XL',                  brand = 'Albany',          price = 166500,  category = 'suvs'},
    { model = 'dorado',          name = 'Dorado',                        brand = 'Bravado',         price = 137500,  category = 'suvs'},
    { model = 'vivanite',        name = 'Vivanite',                      brand = 'Karin',           price = 160500,  category = 'suvs'},
    -- { model = 'castigator',      name = 'Castigator',                    brand = 'Canis',           price = 160500,  category = 'suvs'},
    --- Coupes (3)
    { model = 'cogcabrio',       name = 'Cognoscenti Cabrio',            brand = 'Enus',            price = 550000,   category = 'coupes'},
    { model = 'exemplar',        name = 'Exemplar',                      brand = 'Dewbauchee',      price = 550000,   category = 'coupes'},
    { model = 'f620',            name = 'F620',                          brand = 'Ocelot',          price = 550000,   category = 'coupes'},
    { model = 'felon',           name = 'Felon',                         brand = 'Lampadati',       price = 250000,   category = 'coupes'},
    { model = 'felon2',          name = 'Felon GT',                      brand = 'Lampadati',       price = 350000,   category = 'coupes'},
    { model = 'jackal',          name = 'Jackal',                        brand = 'Ocelot',          price = 350000,   category = 'coupes'},
    { model = 'oracle2',         name = 'Oracle XS',                     brand = 'Übermacht',       price = 250000,   category = 'coupes'},
    { model = 'sentinel',        name = 'Sentinel',                      brand = 'Übermacht',       price = 450000,   category = 'coupes'},
    { model = 'sentinel2',       name = 'Sentinel XS',                   brand = 'Übermacht',       price = 550000,   category = 'coupes'},
    { model = 'windsor',         name = 'Windsor',                       brand = 'Enus',            price = 550000,   category = 'coupes'},
    { model = 'windsor2',        name = 'Windsor Drop',                  brand = 'Enus',            price = 550000,   category = 'coupes'},
    { model = 'zion',            name = 'Zion',                          brand = 'Übermacht',       price = 550000,   category = 'coupes'},
    { model = 'zion2',           name = 'Zion Cabrio',                   brand = 'Übermacht',       price = 550000,   category = 'coupes'},
    { model = 'previon',         name = 'Previon',                       brand = 'Karin',           price = 149000,  category = 'coupes'},
    { model = 'champion',        name = 'Champion',                      brand = 'Dewbauchee',      price = 205000,  category = 'coupes'},
    { model = 'futo',            name = 'Futo',                          brand = 'Karin',           price = 550000,   category = 'coupes'},
    { model = 'sentinel3',       name = 'Sentinel Classic',              brand = 'Übermacht',       price = 550000,   category = 'coupes'},
    { model = 'kanjosj',         name = 'Kanjo SJ',                      brand = 'Dinka',           price = 143000,  category = 'coupes'},
    { model = 'postlude',        name = 'Postlude',                      brand = 'Dinka',           price = 550000,   category = 'coupes'},
    { model = 'tahoma',          name = 'Tahoma Coupe',                  brand = 'Declasse',        price = 550000,   category = 'coupes'},
    { model = 'broadway',        name = 'Broadway',                      brand = 'Classique',       price = 550000,   category = 'coupes'},
    { model = 'fr36',            name = 'FR36',                          brand = 'Fathom',          price = 161000,  category = 'coupes'},
    --- Muscle (4)
    { model = 'blade',           name = 'Blade',                         brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'buccaneer',       name = 'Buccaneer',                     brand = 'Albany',          price = 550000,   category = 'muscle'},
    { model = 'buccaneer2',      name = 'Buccaneer Rider',               brand = 'Albany',          price = 550000,   category = 'muscle'},
    { model = 'chino',           name = 'Chino',                         brand = 'Vapid',           price = 550000,    category = 'muscle'},
    { model = 'chino2',          name = 'Chino Luxe',                    brand = 'Vapid',           price = 550000,    category = 'muscle'},
    { model = 'clique',          name = 'Clique',                        brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'coquette3',       name = 'Coquette BlackFin',             brand = 'Invetero',        price = 550000,  category = 'muscle'},
    { model = 'deviant',         name = 'Deviant',                       brand = 'Schyster',        price = 550000,   category = 'muscle'},
    { model = 'dominator',       name = 'Dominator',                     brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'dominator2',      name = 'Pißwasser Dominator',           brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'dominator3',      name = 'Dominator GTX',                 brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'dominator4',      name = 'Dominator Arena',               brand = 'Vapid',           price = 200000,  category = 'muscle'},
    { model = 'dominator7',      name = 'Dominator ASP',                 brand = 'Vapid',           price = 550000,  category = 'muscle'},
    { model = 'dominator8',      name = 'Dominator GTT',                 brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'dukes',           name = 'Dukes',                         brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'dukes2',          name = 'Duke O\'Death',                 brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'dukes3',          name = 'Beater Dukes',                  brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'faction',         name = 'Faction',                       brand = 'Willard',         price = 550000,   category = 'muscle'},
    { model = 'faction2',        name = 'Faction Rider',                 brand = 'Willard',         price = 550000,   category = 'muscle'},
    { model = 'faction3',        name = 'Faction Custom Donk',           brand = 'Willard',         price = 550000,   category = 'muscle'},
    { model = 'ellie',           name = 'Ellie',                         brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'gauntlet',        name = 'Gauntlet',                      brand = 'Bravado',         price = 550000,   category = 'muscle'},
    { model = 'gauntlet2',       name = 'Redwood Gauntlet',              brand = 'Bravado',         price = 550000,   category = 'muscle'},
    { model = 'gauntlet3',       name = 'Classic Gauntlet',              brand = 'Bravado',         price = 550000,   category = 'muscle'},
    { model = 'gauntlet4',       name = 'Gauntlet Hellfire',             brand = 'Bravado',         price = 550000,   category = 'muscle'},
    { model = 'gauntlet5',       name = 'Gauntlet Classic Custom',       brand = 'Bravado',         price = 550000,  category = 'muscle'},
    { model = 'hermes',          name = 'Hermes',                        brand = 'Albany',          price = 535000,  category = 'muscle'},
    { model = 'hotknife',        name = 'Hotknife',                      brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'hustler',         name = 'Hustler',                       brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'impaler',         name = 'Impaler',                       brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'impaler2',        name = 'Impaler Arena',                 brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'impaler3',        name = 'Impaler Future Shock',          brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'impaler4',        name = 'Impaler Nightmare',             brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'imperator',       name = 'Imperator Arena',               brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'imperator2',      name = 'imperator Future Shock',        brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'imperator3',      name = 'Imperator Nightmare',           brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'lurcher',         name = 'Lurcher',                       brand = 'Bravado',         price = 550000,   category = 'muscle'},
    { model = 'nightshade',      name = 'Nightshade',                    brand = 'Imponte',         price = 123400,   category = 'muscle'},
    { model = 'phoenix',         name = 'Phoenix',                       brand = 'Imponte',         price = 564200,   category = 'muscle'},
    { model = 'picador',         name = 'Picador',                       brand = 'Cheval',          price = 550000,   category = 'muscle'},
    { model = 'ratloader2',      name = 'Ratloader',                     brand = 'Ratloader2',      price = 550000,   category = 'muscle'},
    { model = 'ruiner',          name = 'Ruiner',                        brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'ruiner2',         name = 'Ruiner 2000',                   brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'sabregt',         name = 'Sabre GT Turbo',                brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'sabregt2',        name = 'Sabre GT Turbo Custom',         brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'slamvan',         name = 'Slam Van',                      brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'slamvan2',        name = 'Lost Slam Van',                 brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'slamvan3',        name = 'Slam Van Custom',               brand = 'Vapid',           price = 550000,   category = 'muscle'},
    { model = 'stalion',         name = 'Stallion',                      brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'stalion2',        name = 'Stallion Burgershot',           brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'tampa',           name = 'Tampa',                         brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'tulip',           name = 'Tulip',                         brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'vamos',           name = 'Vamos',                         brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'vigero',          name = 'Vigero',                        brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'virgo',           name = 'Virgo',                         brand = 'Albany',          price = 550000,   category = 'muscle'},
    { model = 'virgo2',          name = 'Virgo Custom Classic',          brand = 'Dundreary',       price = 550000,   category = 'muscle'},
    { model = 'virgo3',          name = 'Virgo Classic',                 brand = 'Dundreary',       price = 550000,   category = 'muscle'},
    { model = 'voodoo',          name = 'Voodoo',                        brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'yosemite',        name = 'Yosemite',                      brand = 'Declasse',        price = 550000,   category = 'muscle'},
    -- { model = 'yosemite2',       name = 'Yosemite Drift',                brand = 'Declasse',        price = 55000,   category = 'muscle'},
    { model = 'buffalo4',        name = 'Buffalo STX',                   brand = 'Bravado',         price = 345000,  category = 'muscle'},
    { model = 'manana',          name = 'Manana',                        brand = 'Albany',          price = 550000,   category = 'muscle'},
    { model = 'manana2',         name = 'Manana Custom',                 brand = 'Albany',          price = 550000,   category = 'muscle'},
    { model = 'tampa2',          name = 'Drift Tampa',                   brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'ruiner4',         name = 'Ruiner ZZ-8',                   brand = 'Imponte',         price = 550000,   category = 'muscle'},
    { model = 'vigero2',         name = 'Vigero ZX',                     brand = 'Declasse',        price = 105000,  category = 'muscle'},
    { model = 'weevil2',         name = 'Weevil Custom',                 brand = 'BF',              price = 550000,   category = 'muscle'},
    { model = 'buffalo5',        name = 'Buffalo EVX',                   brand = 'Bravado',         price = 214000,  category = 'muscle'},
    { model = 'tulip2',          name = 'Tulip M-100',                   brand = 'Declasse',        price = 550000,   category = 'muscle'},
    { model = 'clique2',         name = 'Clique Wagon',                  brand = 'Vapid',           price = 102500,  category = 'muscle'},
    { model = 'brigham',         name = 'Brigham',                       brand = 'Albany',          price = 149900,  category = 'muscle'},
    { model = 'greenwood',       name = 'Greenwood',                     brand = 'Bravado',         price = 105000,  category = 'muscle'},
    { model = 'dominator9',      name = 'Dominator GT',                  brand = 'Vapid',           price = 219500,  category = 'muscle'},
    { model = 'impaler6',        name = 'Impaler LX',                    brand = 'Declasse',        price = 146500,  category = 'muscle'},
    { model = 'vigero3',         name = 'Vigero ZX Convertible',         brand = 'Declasse',        price = 229500,  category = 'muscle'},
    --- Sports Classic (5)
    { model = 'ardent',          name = 'Ardent',                        brand = 'Ocelot',          price = 200000,   category = 'sportsclassics'},
    { model = 'btype',           name = 'Roosevelt',                     brand = 'Albany',          price = 200000,   category = 'sportsclassics'},
    { model = 'btype2',          name = 'Franken Stange',                brand = 'Albany',          price = 200000,   category = 'sportsclassics'},
    { model = 'btype3',          name = 'Roosevelt Valor',               brand = 'Albany',          price = 200000,   category = 'sportsclassics'},
    { model = 'casco',           name = 'Casco',                         brand = 'Lampadati',       price = 200000,  category = 'sportsclassics'},
    { model = 'deluxo',          name = 'Deluxo',                        brand = 'Imponte',         price = 200000,   category = 'sportsclassics'},
    { model = 'dynasty',         name = 'Dynasty',                       brand = 'Weeny',           price = 200000,   category = 'sportsclassics'},
    { model = 'fagaloa',         name = 'Fagaloa',                       brand = 'Vulcar',          price = 200000,   category = 'sportsclassics'},
    { model = 'feltzer3',        name = 'Stirling GT',                   brand = 'Benefactor',      price = 115000,  category = 'sportsclassics'},
    { model = 'gt500',           name = 'GT500',                         brand = 'Grotti',          price = 130000,  category = 'sportsclassics'},
    { model = 'infernus2',       name = 'Infernus Classic',              brand = 'Pegassi',         price = 245000,  category = 'sportsclassics'},
    { model = 'jb700',           name = 'JB 700',                        brand = 'Dewbauchee',      price = 240000,  category = 'sportsclassics'},
    { model = 'jb7002',          name = 'JB 700W',                       brand = 'Dewbauchee',      price = 200000,   category = 'sportsclassics'},
    { model = 'mamba',           name = 'Mamba',                         brand = 'Declasse',        price = 140000,  category = 'sportsclassics'},
    { model = 'michelli',        name = 'Michelli GT',                   brand = 'Lampadati',       price = 200000,   category = 'sportsclassics'},
    { model = 'monroe',          name = 'Monroe',                        brand = 'Pegassi',         price = 115000,  category = 'sportsclassics'},
    { model = 'nebula',          name = 'Nebula',                        brand = 'Vulcar',          price = 200000,   category = 'sportsclassics'},
    { model = 'peyote',          name = 'Peyote',                        brand = 'Vapid',           price = 200000,   category = 'sportsclassics'},
    { model = 'peyote3',         name = 'Peyote Custom',                 brand = 'Vapid',           price = 250000,   category = 'sportsclassics'},
    { model = 'pigalle',         name = 'Pigalle',                       brand = 'Lampadati',       price = 200000,   category = 'sportsclassics'},
    { model = 'rapidgt3',        name = 'Rapid GT Classic',              brand = 'Dewbauchee',      price = 280000,   category = 'sportsclassics'},
    { model = 'retinue',         name = 'Retinue',                       brand = 'Vapid',           price = 200000,   category = 'sportsclassics'},
    { model = 'retinue2',        name = 'Retinue MKII',                  brand = 'Vapid',           price = 200000,   category = 'sportsclassics'},
    { model = 'savestra',        name = 'Savestra',                      brand = 'Annis',           price = 200000,   category = 'sportsclassics'},
    { model = 'stinger',         name = 'Stinger',                       brand = 'Grotti',          price = 200000,   category = 'sportsclassics'},
    { model = 'stingergt',       name = 'Stinger GT',                    brand = 'Grotti',          price = 200000,   category = 'sportsclassics'},
    { model = 'stromberg',       name = 'Stromberg',                     brand = 'Ocelot',          price = 200000,   category = 'sportsclassics'},
    { model = 'swinger',         name = 'Swinger',                       brand = 'Ocelot',          price = 221000,  category = 'sportsclassics'},
    { model = 'torero',          name = 'Torero',                        brand = 'Pegassi',         price = 200000,   category = 'sportsclassics'},
    { model = 'tornado',         name = 'Tornado',                       brand = 'Declasse',        price = 200000,   category = 'sportsclassics'},
    { model = 'turismo2',        name = 'Turismo Classic',               brand = 'Grotti',          price = 170000,  category = 'sportsclassics'},
    { model = 'viseris',         name = 'Viseris',                       brand = 'Lampadati',       price = 210000,  category = 'sportsclassics'},
    { model = 'z190',            name = '190Z',                          brand = 'Karin',           price = 200000,   category = 'sportsclassics'},
    { model = 'ztype',           name = 'Z-Type',                        brand = 'Truffade',        price = 270000,  category = 'sportsclassics'},
    { model = 'zion3',           name = 'Zion Classic',                  brand = 'Übermacht',       price = 200000,   category = 'sportsclassics'},
    { model = 'cheburek',        name = 'Cheburek',                      brand = 'Rune',            price = 200000,    category = 'sportsclassics'},
    { model = 'toreador',        name = 'Toreador',                      brand = 'Pegassi',         price = 200000,   category = 'sportsclassics'},
    { model = 'peyote2',         name = 'Peyote Gasser',                 brand = 'Vapid',           price = 200000,   category = 'sportsclassics'},
    { model = 'coquette2',       name = 'Coquette Classic',              brand = 'Invetero',        price = 165000,  category = 'sportsclassics'},
    -- { model = 'envisage',        name = 'Envisage',                      brand = 'Bollokan',        price = 450000,  category = 'sportsclassics'},
    -- { model = 'driftnebula',     name = 'Nebula Turbo',                  brand = 'Vulcar',          price = 550000,  category = 'sportsclassics'},
    --- Sports (6)
    { model = 'alpha',           name = 'Alpha',                         brand = 'Albany',          price = 530000,   category = 'sports'},
    { model = 'banshee',         name = 'Banshee',                       brand = 'Bravado',         price = 560000,   category = 'sports'},
    { model = 'bestiagts',       name = 'Bestia GTS',                    brand = 'Grotti',          price = 370000,   category = 'sports'},
    { model = 'buffalo',         name = 'Buffalo',                       brand = 'Bravado',         price = 480750,   category = 'sports'},
    { model = 'buffalo2',        name = 'Buffalo S',                     brand = 'Bravado',         price = 340500,   category = 'sports'},
    { model = 'carbonizzare',    name = 'Carbonizzare',                  brand = 'Grotti',          price = 455000,  category = 'sports'},
    { model = 'comet2',          name = 'Comet',                         brand = 'Pfister',         price = 430000,  category = 'sports'},
    { model = 'comet3',          name = 'Comet Retro Custom',            brand = 'Pfister',         price = 575000,  category = 'sports'},
    { model = 'comet4',          name = 'Comet Safari',                  brand = 'Pfister',         price = 610000,  category = 'sports'},
    { model = 'comet5',          name = 'Comet SR',                      brand = 'Pfister',         price = 755000,  category = 'sports'},
    { model = 'coquette',        name = 'Coquette',                      brand = 'Invetero',        price = 445000,  category = 'sports'},
    { model = 'coquette4',       name = 'Coquette D10',                  brand = 'Invetero',        price = 420000,  category = 'sports'},
    { model = 'drafter',         name = '8F Drafter',                    brand = 'Obey',            price = 820000,   category = 'sports'},
    { model = 'elegy',           name = 'Elegy Retro Custom',            brand = 'Annis',           price = 445000,  category = 'sports'},
    { model = 'elegy2',          name = 'Elegy RH8',                     brand = 'Annis',           price = 450000,  category = 'sports'},
    { model = 'feltzer2',        name = 'Feltzer',                       brand = 'Benefactor',      price = 497000,   category = 'sports'},
    { model = 'flashgt',         name = 'Flash GT',                      brand = 'Vapid',           price = 348000,   category = 'sports'},
    { model = 'furoregt',        name = 'Furore GT',                     brand = 'Lampadati',       price = 478000,   category = 'sports'},
    { model = 'gb200',           name = 'GB 200',                        brand = 'Vapid',           price = 140000,  category = 'sports'},
    { model = 'komoda',          name = 'Komoda',                        brand = 'Lampadati',       price = 545000,   category = 'sports'},
    { model = 'imorgon',         name = 'Imorgon',                       brand = 'Överflöd',        price = 220000,  category = 'sports'},
    { model = 'italigto',        name = 'Itali GTO',                     brand = 'Progen',          price = 460000,  category = 'sports'},
    { model = 'jugular',         name = 'Jugular',                       brand = 'Ocelot',          price = 500000,   category = 'sports'},
    { model = 'jester',          name = 'Jester',                        brand = 'Dinka',           price = 332250,  category = 'sports'},
    { model = 'jester2',         name = 'Jester Racecar',                brand = 'Dinka',           price = 410000,  category = 'sports'},
    { model = 'jester3',         name = 'Jester Classic',                brand = 'Dinka',           price = 555000,   category = 'sports'},
    { model = 'khamelion',       name = 'Khamelion',                     brand = 'Hijak',           price = 390000,   category = 'sports'},
    { model = 'kuruma',          name = 'Kuruma',                        brand = 'Karin',           price = 272000,   category = 'sports'},
    { model = 'locust',          name = 'Locust',                        brand = 'Ocelot',          price = 200000,  category = 'sports'},
    { model = 'lynx',            name = 'Lynx',                          brand = 'Ocelot',          price = 150000,  category = 'sports'},
    { model = 'massacro',        name = 'Massacro',                      brand = 'Dewbauchee',      price = 110000,  category = 'sports'},
    { model = 'massacro2',       name = 'Massacro Racecar',              brand = 'Dewbauchee',      price = 380000,   category = 'sports'},
    { model = 'neo',             name = 'Neo',                           brand = 'Vysser',          price = 230000,  category = 'sports'},
    { model = 'neon',            name = 'Neon',                          brand = 'Pfister',         price = 5000000,  category = 'sports'},
    { model = 'ninef',           name = '9F',                            brand = 'Obey',            price = 395000,   category = 'sports'},
    { model = 'ninef2',          name = '9F Cabrio',                     brand = 'Obey',            price = 405000,  category = 'sports'},
    { model = 'omnis',           name = 'Omnis',                         brand = 'Wow',             price = 340000,   category = 'sports'},
    { model = 'paragon',         name = 'Paragon',                       brand = 'Enus',            price = 360000,   category = 'sports'},
    { model = 'pariah',          name = 'Pariah',                        brand = 'Ocelot',          price = 490000,   category = 'sports'},
    { model = 'penumbra',        name = 'Penumbra',                      brand = 'Maibatsu',        price = 522000,   category = 'sports'},
    { model = 'penumbra2',       name = 'Penumbra FF',                   brand = 'Maibatsu',        price = 530000,   category = 'sports'},
    { model = 'rapidgt',         name = 'Rapid GT',                      brand = 'Dewbauchee',      price = 386000,   category = 'sports'},
    { model = 'rapidgt2',        name = 'Rapid GT Convertible',          brand = 'Dewbauchee',      price = 492000,   category = 'sports'},
    { model = 'raptor',          name = 'Raptor',                        brand = 'BF',              price = 590000,   category = 'sports'},
    { model = 'revolter',        name = 'Revolter',                      brand = 'Übermacht',       price = 295000,   category = 'sports'},
    { model = 'ruston',          name = 'Ruston',                        brand = 'Hijak',           price = 4130000,  category = 'sports'},
    { model = 'schafter3',       name = 'Schafter V12',                  brand = 'Benefactor',      price = 535000,   category = 'sports'},
    { model = 'schafter4',       name = 'Schafter LWB',                  brand = 'Benefactor',      price = 321000,   category = 'sports'},
    { model = 'schlagen',        name = 'Schlagen GT',                   brand = 'Benefactor',      price = 160000,  category = 'sports'},
    { model = 'schwarzer',       name = 'Schwartzer',                    brand = 'Benefactor',      price = 247000,   category = 'sports'},
    { model = 'seven70',         name = 'Seven-70',                      brand = 'Dewbauchee',      price = 140000,  category = 'sports'},
    { model = 'specter',         name = 'Specter',                       brand = 'Dewbauchee',      price = 160000,  category = 'sports'},
    { model = 'streiter',        name = 'Streiter',                      brand = 'Benefactor',      price = 240000,   category = 'sports'},
    { model = 'sugoi',           name = 'Sugoi',                         brand = 'Dinka',           price = 805000,   category = 'sports'},
    { model = 'sultan',          name = 'Sultan',                        brand = 'Karin',           price = 850000,   category = 'sports'},
    { model = 'sultan2',         name = 'Sultan Custom',                 brand = 'Karin',           price = 1005000,   category = 'sports'},
    { model = 'surano',          name = 'Surano',                        brand = 'Benefactor',      price = 280000,   category = 'sports'},
    { model = 'tropos',          name = 'Tropos Rallye',                 brand = 'Lampadati',       price = 465000,   category = 'sports'},
    { model = 'verlierer2',      name = 'Verlierer',                     brand = 'Bravado',         price = 490500,   category = 'sports'},
    { model = 'vstr',            name = 'V-STR',                         brand = 'Albany',          price = 480000,   category = 'sports'},
    { model = 'italirsx',        name = 'Itali RSX',                     brand = 'Progen',          price = 426000,  category = 'sports'},
    { model = 'zr350',           name = 'ZR350',                         brand = 'Annis',           price = 438000,   category = 'sports'},
    { model = 'calico',          name = 'Calico GTF',                    brand = 'Karin',           price = 839000,   category = 'sports'},
    { model = 'futo2',           name = 'Futo GTX',                      brand = 'Karin',           price = 839000,   category = 'sports'},
    { model = 'euros',           name = 'Euros',                         brand = 'Annis',           price = 880000,   category = 'sports'},
    { model = 'jester4',         name = 'Jester RR',                     brand = 'Dinka',           price = 8240000,  category = 'sports'},
    { model = 'remus',           name = 'Remus',                         brand = 'Annis',           price = 848000,   category = 'sports'},
    { model = 'comet6',          name = 'Comet S2',                      brand = 'Pfister',         price = 8230000,  category = 'sports'},
    { model = 'growler',         name = 'Growler',                       brand = 'Pfister',         price = 8205000,  category = 'sports'},
    { model = 'vectre',          name = 'Vectre',                        brand = 'Emperor',         price = 380000,   category = 'sports'},
    { model = 'cypher',          name = 'Cypher',                        brand = 'Übermacht',       price = 155000,  category = 'sports'},
    { model = 'sultan3',         name = 'Sultan Classic Custom',         brand = 'Karin',           price = 456000,   category = 'sports'},
    { model = 'rt3000',          name = 'RT3000',                        brand = 'Dinka',           price = 265000,   category = 'sports'},
    { model = 'sultanrs',        name = 'Sultan RS',                     brand = 'Karin',           price = 576500,   category = 'sports'},
    { model = 'visione',         name = 'Visione',                       brand = 'Grotti',          price = 750000,  category = 'sports'},
    { model = 'cheetah2',        name = 'Cheetah Classic',               brand = 'Grotti',          price = 195000,  category = 'sports'},
    { model = 'stingertt',       name = 'Itali GTO Stinger TT',          brand = 'Maibatsu',        price = 238000,  category = 'sports'},
    { model = 'omnisegt',        name = 'Omnis e-GT',                    brand = 'Obey',            price = 185000,  category = 'sports'},
    { model = 'sentinel4',       name = 'Sentinel Classic Widebody',     brand = 'Übermacht',       price = 140000,  category = 'sports'},
    { model = 'sm722',           name = 'SM722',                         brand = 'Benefactor',      price = 125000,  category = 'sports'},
    { model = 'tenf',            name = '10F',                           brand = 'Obey',            price = 185000,  category = 'sports'},
    { model = 'tenf2',           name = '10F Widebody',                  brand = 'Obey',            price = 215000,  category = 'sports'},
    { model = 'everon2',         name = 'Everon Hotring',                brand = 'Karin',           price = 280000,   category = 'sports'},
    { model = 'issi8',           name = 'Issi Rally',                    brand = 'Weeny',           price = 210000,   category = 'sports'},
    { model = 'corsita',         name = 'Corsita',                       brand = 'Lampadati',       price = 390000,   category = 'sports'},
    { model = 'gauntlet6',       name = 'Hotring Hellfire',              brand = 'Bravado',         price = 281000,  category = 'sports'},
    { model = 'coureur',         name = 'La Coureuse',                   brand = 'Penaud',          price = 199000,  category = 'sports'},
    { model = 'r300',            name = '300R',                          brand = 'Annis',           price = 556000,   category = 'sports'},
    { model = 'panthere',        name = 'Panthere',                      brand = 'Toundra',         price = 555000,   category = 'sports'},
    -- { model = 'driftsentinel',   name = 'Drift Sentinel Classic',        brand = 'Ubermacht',       price = 550000,  category = 'sports'},
    -- { model = 'paragon3',        name = 'Paragon S',                     brand = 'Enus',            price = 720000,  category = 'sports'},
    -- { model = 'eurosX32',        name = 'Euros X32',                     brand = 'Annis',           price = 480000,  category = 'sports'},
    -- { model = 'vorschlaghammer', name = 'Vorschlaghammer',               brand = 'Pfister',         price = 550000,  category = 'sports'},
    -- { model = 'driftcypher',     name = 'Drift Cypher',                  brand = 'Ubermacht',       price = 660000,  category = 'sports'},
    -- { model = 'coquette5',       name = 'Coquette D1',                   brand = 'Invetero',        price = 720000,  category = 'sports'},
    -- { model = 'pipistrello',     name = 'Pipistrello',                   brand = 'Overflod',        price = 440000,  category = 'sports'},
    -- { model = 'niobe',           name = 'Niobe',                         brand = 'Ubermacht',       price = 380000,  category = 'sports'},
    -- { model = 'driftvorschlag',  name = 'Vorschlaghammer',               brand = 'Pfister',         price = 350000,  category = 'sports'},
    --- Super (7)
    { model = 'adder',           name = 'Adder',                         brand = 'Truffade',        price = 680000,  category = 'super'},
    { model = 'autarch',         name = 'Autarch',                       brand = 'Överflöd',        price = 524000,  category = 'super'},
    { model = 'banshee2',        name = 'Banshee 900R',                  brand = 'Bravado',         price = 520000,  category = 'super'},
    { model = 'bullet',          name = 'Bullet',                        brand = 'Vapid',           price = 420000,  category = 'super'},
    { model = 'cheetah',         name = 'Cheetah',                       brand = 'Grotti',          price = 614000,  category = 'super'},
    { model = 'cyclone',         name = 'Cyclone',                       brand = 'Coil',            price = 800000,  category = 'super'},
    { model = 'entity2',         name = 'Entity XXR',                    brand = 'Överflöd',        price = 864000,  category = 'super'},
    { model = 'entityxf',        name = 'Entity XF',                     brand = 'Överflöd',        price = 780000,  category = 'super'},
    { model = 'emerus',          name = 'Emerus',                        brand = 'Progen',          price = 620000,  category = 'super'},
    { model = 'fmj',             name = 'FMJ',                           brand = 'Vapid',           price = 525000,  category = 'super'},
    { model = 'furia',           name = 'Furia',                         brand = 'Grotti',          price = 730000,  category = 'super'},
    { model = 'gp1',             name = 'GP1',                           brand = 'Progen',          price = 610000,  category = 'super'},
    { model = 'infernus',        name = 'Infernus',                      brand = 'Pegassi',         price = 835000,  category = 'super'},
    { model = 'italigtb',        name = 'Itali GTB',                     brand = 'Progen',          price = 770000,  category = 'super'},
    { model = 'italigtb2',       name = 'Itali GTB Custom',              brand = 'Progen',          price = 750000,  category = 'super'},
    { model = 'krieger',         name = 'Krieger',                       brand = 'Benefactor',      price = 622000,  category = 'super'},
    { model = 'le7b',            name = 'RE-7B',                         brand = 'Annis',           price = 560000,  category = 'super'},
    { model = 'nero',            name = 'Nero',                          brand = 'Truffade',        price = 500000,  category = 'super'},
    { model = 'nero2',           name = 'Nero Custom',                   brand = 'Truffade',        price = 560000,  category = 'super'},
    { model = 'osiris',          name = 'Osiris',                        brand = 'Pegassi',         price = 520000,  category = 'super'},
    { model = 'penetrator',      name = 'Penetrator',                    brand = 'Ocelot',          price = 530000,  category = 'super'},
    { model = 'pfister811',      name = '811',                           brand = 'Pfister',         price = 520000,  category = 'super'},
    { model = 'prototipo',       name = 'X80 Proto',                     brand = 'Grotti',          price = 535000,  category = 'super'},
    { model = 'reaper',          name = 'Reaper',                        brand = 'Pegassi',         price = 500000,  category = 'super'},
    { model = 's80',             name = 'S80RR',                         brand = 'Annis',           price = 205000,  category = 'super'},
    { model = 'sc1',             name = 'SC1',                           brand = 'Übermacht',       price = 290000,   category = 'super'},
    { model = 'sheava',          name = 'ETR1',                          brand = 'Emperor',         price = 220000,  category = 'super'},
    { model = 't20',             name = 'T20',                           brand = 'Progen',          price = 1650000, category = 'super'},
    { model = 'taipan',          name = 'Taipan',                        brand = 'Cheval',          price = 1850000, category = 'super'},
    { model = 'tempesta',        name = 'Tempesta',                      brand = 'Pegassi',         price = 120000,  category = 'super'},
    { model = 'tezeract',        name = 'Tezeract',                      brand = 'Pegassi',         price = 220000,  category = 'super'},
    { model = 'thrax',           name = 'Thrax',                         brand = 'Truffade',        price = 180000,  category = 'super'},
    { model = 'tigon',           name = 'Tigon',                         brand = 'Lampadati',       price = 240000,  category = 'super'},
    { model = 'turismor',        name = 'Turismo R',                     brand = 'Grotti',          price = 140000,  category = 'super'},
    { model = 'tyrant',          name = 'Tyrant',                        brand = 'Överflöd',        price = 2100000, category = 'super'},
    { model = 'tyrus',           name = 'Tyrus',                         brand = 'Progen',          price = 230000,  category = 'super'},
    { model = 'vacca',           name = 'Vacca',                         brand = 'Pegassi',         price = 105000,  category = 'super'},
    { model = 'vagner',          name = 'Vagner',                        brand = 'Dewbauchee',      price = 1660000, category = 'super'},
    { model = 'voltic',          name = 'Voltic',                        brand = 'Coil',            price = 120000,  category = 'super'},
    { model = 'xa21',            name = 'XA-21',                         brand = 'Ocelot',          price = 180000,  category = 'super'},
    { model = 'zentorno',        name = 'Zentorno',                      brand = 'Pegassi',         price = 340000,  category = 'super'},
    { model = 'zorrusso',        name = 'Zorrusso',                      brand = 'Pegassi',         price = 277000,  category = 'super'},
    { model = 'ignus',           name = 'Ignus',                         brand = 'Pegassi',         price = 1120000, category = 'super'},
    { model = 'zeno',            name = 'Zeno',                          brand = 'Överflöd',        price = 1350000, category = 'super'},
    { model = 'deveste',         name = 'Deveste',                       brand = 'Principe',        price = 234000,  category = 'super'},
    { model = 'lm87',            name = 'LM87',                          brand = 'Benefactor',      price = 155000,  category = 'super'},
    { model = 'torero2',         name = 'Torero XO',                     brand = 'Pegassi',         price = 245000,  category = 'super'},
    { model = 'entity3',         name = 'Entity MT',                     brand = 'Overflod',        price = 200000,  category = 'super'},
    { model = 'virtue',          name = 'Virtue',                        brand = 'Ocelot',          price = 72000,   category = 'super'},
    { model = 'turismo3',        name = 'Turismo Omaggio',               brand = 'Grotti',          price = 284500,  category = 'super'},
    --- Motorcycles (8)
    { model = 'akuma',           name = 'Akuma',                         brand = 'Dinka',           price = 55000,   category = 'motorcycles'},
    { model = 'avarus',          name = 'Avarus',                        brand = 'LCC',             price = 20000,   category = 'motorcycles'},
    { model = 'bagger',          name = 'Bagger',                        brand = 'WMC',             price = 13500,   category = 'motorcycles'},
    { model = 'bati',            name = 'Bati 801',                      brand = 'Pegassi',         price = 24000,   category = 'motorcycles'},
    { model = 'bati2',           name = 'Bati 801RR',                    brand = 'Pegassi',         price = 19000,   category = 'motorcycles'},
    { model = 'bf400',           name = 'BF400',                         brand = 'Nagasaki',        price = 22000,   category = 'motorcycles'},
    { model = 'carbonrs',        name = 'Carbon RS',                     brand = 'Nagasaki',        price = 22000,   category = 'motorcycles'},
    { model = 'chimera',         name = 'Chimera',                       brand = 'Nagasaki',        price = 21000,   category = 'motorcycles'},
    { model = 'cliffhanger',     name = 'Cliffhanger',                   brand = 'Western',         price = 28500,   category = 'motorcycles'},
    { model = 'daemon',          name = 'Daemon',                        brand = 'WMC',             price = 14000,   category = 'motorcycles'},
    { model = 'daemon2',         name = 'Daemon Custom',                 brand = 'Western',         price = 23000,   category = 'motorcycles'},
    { model = 'defiler',         name = 'Defiler',                       brand = 'Shitzu',          price = 30000,   category = 'motorcycles'},
    { model = 'deathbike',       name = 'Deathbike Apocalypse',          brand = 'Deathbike',       price = 30000,   category = 'motorcycles'},
    { model = 'deathbike2',      name = 'Deathbike Future Shock',        brand = 'Deathbike',       price = 30000,   category = 'motorcycles'},
    { model = 'deathbike3',      name = 'Deathbike Nightmare',           brand = 'Deathbike',       price = 30000,   category = 'motorcycles'},
    { model = 'diablous',        name = 'Diablous',                      brand = 'Principe',        price = 30000,   category = 'motorcycles'},
    { model = 'diablous2',       name = 'Diablous Custom',               brand = 'Principe',        price = 38000,   category = 'motorcycles'},
    { model = 'double',          name = 'Double-T',                      brand = 'Dinka',           price = 28000,   category = 'motorcycles'},
    { model = 'enduro',          name = 'Enduro',                        brand = 'Dinka',           price = 5500,    category = 'motorcycles'},
    { model = 'esskey',          name = 'Esskey',                        brand = 'Pegassi',         price = 12000,   category = 'motorcycles'},
    { model = 'faggio',          name = 'Faggio Sport',                  brand = 'Pegassi',         price = 2000,    category = 'motorcycles'},
    { model = 'faggio2',         name = 'Faggio',                        brand = 'Pegassi',         price = 1900,    category = 'motorcycles'},
    { model = 'faggio3',         name = 'Faggio Mod',                    brand = 'Pegassi',         price = 2500,    category = 'motorcycles'},
    { model = 'fcr',             name = 'FCR 1000',                      brand = 'Pegassi',         price = 5000,    category = 'motorcycles'},
    { model = 'fcr2',            name = 'FCR 1000 Custom',               brand = 'Pegassi',         price = 19000,   category = 'motorcycles'},
    { model = 'gargoyle',        name = 'Gargoyle',                      brand = 'Western',         price = 32000,   category = 'motorcycles'},
    { model = 'hakuchou',        name = 'Hakuchou',                      brand = 'Shitzu',          price = 17000,   category = 'motorcycles'},
    { model = 'hakuchou2',       name = 'Hakuchou Drag',                 brand = 'Shitzu',          price = 45000,   category = 'motorcycles'},
    { model = 'hexer',           name = 'Hexer',                         brand = 'LCC',             price = 16000,   category = 'motorcycles'},
    { model = 'innovation',      name = 'Innovation',                    brand = 'LLC',             price = 33500,   category = 'motorcycles'},
    { model = 'lectro',          name = 'Lectro',                        brand = 'Principe',        price = 28000,   category = 'motorcycles'},
    { model = 'manchez',         name = 'Manchez',                       brand = 'Maibatsu',        price = 8300,    category = 'motorcycles'},
    { model = 'nemesis',         name = 'Nemesis',                       brand = 'Principe',        price = 20000,   category = 'motorcycles'},
    { model = 'nightblade',      name = 'Nightblade',                    brand = 'WMC',             price = 23000,   category = 'motorcycles'},
    { model = 'pcj',             name = 'PCJ-600',                       brand = 'Shitzu',          price = 250000,   category = 'motorcycles'},
    { model = 'ratbike',         name = 'Rat Bike',                      brand = 'Western',         price = 250000,    category = 'motorcycles'},
    { model = 'ruffian',         name = 'Ruffian',                       brand = 'Pegassi',         price = 250000,   category = 'motorcycles'},
    { model = 'sanchez',         name = 'Sanchez Livery',                brand = 'Maibatsu',        price = 250000,    category = 'motorcycles'},
    { model = 'sanchez2',        name = 'Sanchez',                       brand = 'Maibatsu',        price = 250000,    category = 'motorcycles'},
    { model = 'sanctus',         name = 'Sanctus',                       brand = 'LCC',             price = 35000,   category = 'motorcycles'},
    { model = 'shotaro',         name = 'Shotaro',                       brand = 'Nagasaki',        price = 320000,  category = 'motorcycles'},
    { model = 'sovereign',       name = 'Sovereign',                     brand = 'WMC',             price = 250000,    category = 'motorcycles'},
    { model = 'stryder',         name = 'Stryder',                       brand = 'Nagasaki',        price = 250000,   category = 'motorcycles'},
    { model = 'thrust',          name = 'Thrust',                        brand = 'Dinka',           price = 250000,   category = 'motorcycles'},
    { model = 'vader',           name = 'Vader',                         brand = 'Shitzu',          price = 250000,    category = 'motorcycles'},
    { model = 'vindicator',      name = 'Vindicator',                    brand = 'Dinka',           price = 250000,   category = 'motorcycles'},
    { model = 'vortex',          name = 'Vortex',                        brand = 'Pegassi',         price = 250000,   category = 'motorcycles'},
    { model = 'wolfsbane',       name = 'Wolfsbane',                     brand = 'Western',         price = 250000,   category = 'motorcycles'},
    { model = 'zombiea',         name = 'Zombie Bobber',                 brand = 'Western',         price = 250000,   category = 'motorcycles'},
    { model = 'zombieb',         name = 'Zombie Chopper',                brand = 'Western',         price = 250000,   category = 'motorcycles'},
    { model = 'manchez2',        name = 'Manchez Scout',                 brand = 'Maibatsu',        price = 250000,   category = 'motorcycles'},
    { model = 'shinobi',         name = 'Shinobi',                       brand = 'Nagasaki',        price = 250000,   category = 'motorcycles'},
    { model = 'reever',          name = 'Reever',                        brand = 'Western',         price = 250000,   category = 'motorcycles'},
    { model = 'manchez3',        name = 'Manchez Scout Classic',         brand = 'Maibatsu',        price = 250000,   category = 'motorcycles'},
    { model = 'powersurge',      name = 'Powersurge',                    brand = 'Western',         price = 250000,    category = 'motorcycles'},
    -- { model = 'pizzaboy',        name = 'Pizza Boy',                     brand = 'Pegassi',         price = 50000,   category = 'motorcycles'},
    --- Off-Road (9)
    { model = 'bfinjection',     name = 'Bf Injection',                  brand = 'Annis',           price = 449000,    category = 'offroad'},
    { model = 'bifta',           name = 'Bifta',                         brand = 'Annis',           price = 515500,   category = 'offroad'},
    { model = 'blazer',          name = 'Blazer',                        brand = 'Annis',           price = 557500,    category = 'offroad'},
    { model = 'blazer2',         name = 'Blazer Lifeguard',              brand = 'Nagasaki',        price = 437000,    category = 'offroad'},
    { model = 'blazer3',         name = 'Blazer Hot Rod',                brand = 'Nagasaki',        price = 127000,    category = 'offroad'},
    { model = 'blazer4',         name = 'Blazer Sport',                  brand = 'Annis',           price = 229250,    category = 'offroad'},
    { model = 'blazer5',         name = 'Blazer Aqua',                   brand = 'Nagasaki',        price = 340000,   category = 'offroad'},
    { model = 'brawler',         name = 'Brawler',                       brand = 'Annis',           price = 440000,   category = 'offroad'},
    { model = 'caracara',        name = 'Caracara',                      brand = 'Vapid',           price = 560000,   category = 'offroad'},
    { model = 'caracara2',       name = 'Caracara 4x4',                  brand = 'Vapid',           price = 580000,   category = 'offroad'},
    { model = 'dubsta3',         name = 'Dubsta 6x6',                    brand = 'Annis',           price = 434000,   category = 'offroad'},
    { model = 'dune',            name = 'Dune Buggy',                    brand = 'Annis',           price = 414000,   category = 'offroad'},
    { model = 'everon',          name = 'Everon',                        brand = 'Karin',           price = 360000,   category = 'offroad'},
    { model = 'freecrawler',     name = 'Freecrawler',                   brand = 'Canis',           price = 424000,   category = 'offroad'},
    { model = 'hellion',         name = 'Hellion',                       brand = 'Annis',           price = 438000,   category = 'offroad'},
    { model = 'kalahari',        name = 'Kalahari',                      brand = 'Canis',           price = 514000,   category = 'offroad'},
    { model = 'kamacho',         name = 'Kamacho',                       brand = 'Canis',           price = 550000,   category = 'offroad'},
    { model = 'mesa3',           name = 'Mesa Merryweather',             brand = 'Canis',           price = 400000,  category = 'offroad'},
    { model = 'outlaw',          name = 'Outlaw',                        brand = 'Nagasaki',        price = 615000,   category = 'offroad'},
    { model = 'rancherxl',       name = 'Rancher XL',                    brand = 'Declasse',        price = 524000,   category = 'offroad'},
    { model = 'rebel2',          name = 'Rebel',                         brand = 'Vapid',           price = 420000,   category = 'offroad'},
    { model = 'riata',           name = 'Riata',                         brand = 'Vapid',           price = 438000,  category = 'offroad'},
    { model = 'sandking',        name = 'Sandking XL',                   brand = 'Vapid',           price = 525000,   category = 'offroad'},
    { model = 'sandking2',       name = 'Sandking SWB',                  brand = 'Vapid',           price = 238000,   category = 'offroad'},
    { model = 'trophytruck',     name = 'Trophy Truck',                  brand = 'Vapid',           price = 460000,   category = 'offroad'},
    { model = 'trophytruck2',    name = 'Desert Raid',                   brand = 'Vapid',           price = 280000,   category = 'offroad'},
    { model = 'vagrant',         name = 'Vagrant',                       brand = 'Maxwell',         price = 450000,   category = 'offroad'},
    { model = 'verus',           name = 'Verus',                         brand = 'Dinka',           price = 320000,   category = 'offroad'},
    { model = 'winky',           name = 'Winky',                         brand = 'Vapid',           price = 410000,   category = 'offroad'},
    { model = 'yosemite3',       name = 'Yosemite Rancher',              brand = 'Declasse',        price = 425000,  category = 'offroad'},
    { model = 'mesa',            name = 'Mesa',                          brand = 'Canis',           price = 412000,   category = 'offroad'},
    { model = 'ratel',           name = 'Ratel',                         brand = 'Vapid',           price = 199000,  category = 'offroad'},
    { model = 'l35',             name = 'Walton L35',                    brand = 'Declasse',        price = 167000,  category = 'offroad'},
    { model = 'monstrociti',     name = 'MonstroCiti',                   brand = 'Maibatsu',        price = 448000,   category = 'offroad'},
    { model = 'draugur',         name = 'Draugur',                       brand = 'Declasse',        price = 399000,   category = 'offroad'},
    { model = 'terminus',        name = 'Terminus',                      brand = 'Canis',           price = 587750,  category = 'offroad'},
    { model = 'yosemite4',       name = 'Yosemite 1500',                 brand = 'Declasse',        price = 487750,  category = 'offroad'},
    --- Industrial (10)
    { model = 'guardian',        name = 'Guardian',                      brand = 'Vapid',           price = 950000,   category = 'industrial'},
    --- Vans (12)
    { model = 'bison',           name = 'Bison',                         brand = 'Bravado',         price = 518000,   category = 'vans'},
    { model = 'bobcatxl',        name = 'Bobcat XL Open',                brand = 'Vapid',           price = 513500,   category = 'vans'},
    { model = 'burrito3',        name = 'Burrito',                       brand = 'Declasse',        price = 650000,    category = 'vans'},
    { model = 'gburrito2',       name = 'Burrito Custom',                brand = 'Declasse',        price = 1001500,   category = 'vans'},
    { model = 'rumpo',           name = 'Rumpo',                         brand = 'Bravado',         price = 559000,    category = 'vans'},
    { model = 'journey',         name = 'Journey',                       brand = 'Zirconium',       price = 556500,    category = 'vans'},
    { model = 'minivan',         name = 'Minivan',                       brand = 'Vapid',           price = 667000,    category = 'vans'},
    { model = 'minivan2',        name = 'Minivan Custom',                brand = 'Vapid',           price = 1000000,   category = 'vans'},
    { model = 'paradise',        name = 'Paradise',                      brand = 'Bravado',         price = 900000,    category = 'vans'},
    { model = 'rumpo3',          name = 'Rumpo Custom',                  brand = 'Bravado',         price = 195000,   category = 'vans'},
    { model = 'speedo',          name = 'Speedo',                        brand = 'Vapid',           price = 510000,   category = 'vans'},
    { model = 'speedo4',         name = 'Speedo Custom',                 brand = 'Vapid',           price = 515000,   category = 'vans'},
    { model = 'surfer',          name = 'Surfer',                        brand = 'BF',              price = 559000,    category = 'vans'},
    { model = 'youga3',          name = 'Youga Classic 4x4',             brand = 'Bravado',         price = 515000,   category = 'vans'},
    { model = 'youga',           name = 'Youga',                         brand = 'Bravado',         price = 558000,    category = 'vans'},
    { model = 'youga2',          name = 'Youga Classic',                 brand = 'Bravado',         price = 514500,   category = 'vans'},
    { model = 'youga4',          name = 'Youga Custom',                  brand = 'Bravado',         price = 585000,   category = 'vans'},
    { model = 'moonbeam',        name = 'Moonbeam',                      brand = 'Declasse',        price = 513000,   category = 'vans'},
    { model = 'moonbeam2',       name = 'Moonbeam Custom',               brand = 'Declasse',        price = 785000,   category = 'vans'},
    { model = 'journey2',        name = 'Journey II',                    brand = 'Zirconium',       price = 607000,    category = 'vans'},
    { model = 'surfer3',         name = 'Surfer Custom',                 brand = 'BF',              price = 715000,   category = 'vans'},
    { model = 'speedo5',         name = 'Speedo Custom',                 brand = 'Vapid',           price = 838000,  category = 'vans'},
    --- Cycles (13)
    { model = 'bmx',             name = 'BMX',                           brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'cruiser',         name = 'Cruiser',                       brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'fixter',          name = 'Fixter',                        brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'scorcher',        name = 'Scorcher',                      brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'tribike',         name = 'Whippet Race Bike',             brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'tribike2',        name = 'Endurex Race Bike',             brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'tribike3',        name = 'Tri-Cycles Race Bike',          brand = 'Bike',            price = 50000,     category = 'cycles'},
    { model = 'inductor',        name = 'Inductor',                      brand = 'Coil',            price = 50000,    category = 'cycles'},
    { model = 'inductor2',       name = 'Junk Energy Inductor',          brand = 'Coil',            price = 50000,    category = 'cycles'},
    --- Boats (14)
    { model = 'avisa',           name = 'Avisa',                         brand = 'Kraken Subs',     price = 40000,   category = 'boats'},
    { model = 'patrolboat',      name = 'Kurtz 31 Patrol Boat',          brand = 'Unknown',         price = 40000,   category = 'boats'},
    { model = 'longfin',         name = 'Longfin',                       brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'tug',             name = 'Tug',                           brand = 'Buckingham',      price = 40000,   category = 'boats'},
    { model = 'toro',            name = 'Toro',                          brand = 'Lampadati',       price = 40000,   category = 'boats'},
    { model = 'toro2',           name = 'Toro Yacht',                    brand = 'Lampadati',       price = 40000,   category = 'boats'},
    { model = 'submersible2',    name = 'Kraken',                        brand = 'Kraken Subs',     price = 40000,   category = 'boats'},
    { model = 'speeder',         name = 'Speeder',                       brand = 'Pegassi',         price = 40000,   category = 'boats'},
    { model = 'speeder2',        name = 'Speeder Yacht',                 brand = 'Pegassi',         price = 40000,   category = 'boats'},
    { model = 'tropic',          name = 'Tropic',                        brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'tropic2',         name = 'Tropic Yacht',                  brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'suntrap',         name = 'Suntrap',                       brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'submersible',     name = 'Submersible',                   brand = 'Kraken Subs',     price = 40000,   category = 'boats'},
    { model = 'squalo',          name = 'Squalo',                        brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'seashark',        name = 'Seashark',                      brand = 'Speedophile',     price = 40000,   category = 'boats'},
    { model = 'seashark3',       name = 'Seashark Yacht',                brand = 'Speedophile',     price = 40000,   category = 'boats'},
    { model = 'marquis',         name = 'Marquis',                       brand = 'Dinka',           price = 40000,   category = 'boats'},
    { model = 'jetmax',          name = 'Jetmax',                        brand = 'Shitzu',          price = 40000,   category = 'boats'},
    { model = 'dinghy',          name = 'Dinghy 2-Seater',               brand = 'Nagasaki',        price = 40000,   category = 'boats'},
    { model = 'dinghy2',         name = 'Dinghy 4-Seater',               brand = 'Nagasaki',        price = 40000,   category = 'boats'},
    { model = 'dinghy3',         name = 'Dinghy (Heist)',                brand = 'Nagasaki',        price = 40000,   category = 'boats'},
    { model = 'dinghy4',         name = 'Dinghy Yacht',                  brand = 'Nagasaki',        price = 40000,   category = 'boats'},
}

for i = 1, #Vehicles do
    ESXShared.Vehicles[Vehicles[i].model] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].category,
        hash = joaat(Vehicles[i].model),
    }
end

for i = 1, #Vehicles do
    ESXShared.VehiclesHash[joaat(Vehicles[i].model)] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].category,
        hash = joaat(Vehicles[i].model),
    }
end