CREATE TABLE IF NOT EXISTS `pvp_stats` (
    `identifier` VARCHAR(60) NOT NULL,
    `name` VARCHAR(100) NOT NULL DEFAULT '',
    `kills` INT NOT NULL DEFAULT 0,
    `deaths` INT NOT NULL DEFAULT 0,
    `th` INT NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
