CREATE TABLE IF NOT EXISTS `keydi_invoices` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `reference` VARCHAR(16) NOT NULL,
    `kind` VARCHAR(16) NOT NULL DEFAULT 'personal',
    `invoice_type` VARCHAR(64) NOT NULL DEFAULT 'Personal',
    `title` VARCHAR(80) NOT NULL,
    `description` VARCHAR(255) DEFAULT NULL,
    `amount` INT NOT NULL DEFAULT 0,
    `vat` INT NOT NULL DEFAULT 0,
    `total` INT NOT NULL DEFAULT 0,
    `due_date` VARCHAR(32) DEFAULT NULL,
    `sender_identifier` VARCHAR(64) NOT NULL,
    `sender_name` VARCHAR(80) NOT NULL,
    `sender_job` VARCHAR(50) DEFAULT NULL,
    `receiver_identifier` VARCHAR(64) NOT NULL,
    `receiver_name` VARCHAR(80) NOT NULL,
    `status` VARCHAR(16) NOT NULL DEFAULT 'unpaid',
    `payment_method` VARCHAR(16) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `paid_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `reference` (`reference`),
    KEY `receiver_identifier` (`receiver_identifier`),
    KEY `sender_identifier` (`sender_identifier`),
    KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
