return {
    LeanFire = false,
    CanDriveBy = false,
    RightLeftRecoil = true,
    RightLeftRecoilRandomiser = true,
    RightLeftRecoilRandomiserChance = 50,
    UseVehicleRecoil = true,
    SuppressorMultiplier = true,

    -- Require police-issued weapon license (meta / DB). Physical card alone does NOT grant use.
    -- Temporarily disabled — set enabled = true when ready to enforce again.
    RequireGunLicense = {
        enabled = false,
        -- ESX meta key under player metadata.licenses
        metaKey = 'weapon',
        -- Physical card item (RP / ID only — not enough to equip guns by itself)
        itemName = 'weaponlicense',
        -- Jobs that can use guns without a civilian license
        exemptJobs = {
            police = true,
            sheriff = true,
            ambulance = false,
        },
        -- Weapon hashes that never need a license (melee / tools / less-lethal)
        exemptWeapons = {
            [`WEAPON_UNARMED`] = true,
            [`WEAPON_STUNGUN`] = true,
            [`WEAPON_STUNGUN_MP`] = true,
            [`WEAPON_TASER`] = true,
            [`WEAPON_FLASHLIGHT`] = true,
            [`WEAPON_NIGHTSTICK`] = true,
            [`WEAPON_FIREEXTINGUISHER`] = true,
            [`WEAPON_PETROLCAN`] = true,
            [`WEAPON_HAZARDCAN`] = true,
            [`WEAPON_FERTILIZERCAN`] = true,
            [`WEAPON_SNOWBALL`] = true,
            [`WEAPON_BALL`] = true,
            [`WEAPON_FLARE`] = true,
            [`WEAPON_KNIFE`] = true,
            [`WEAPON_BAT`] = true,
            [`WEAPON_CROWBAR`] = true,
            [`WEAPON_GOLFCLUB`] = true,
            [`WEAPON_BOTTLE`] = true,
            [`WEAPON_DAGGER`] = true,
            [`WEAPON_HATCHET`] = true,
            [`WEAPON_MACHETE`] = true,
            [`WEAPON_SWITCHBLADE`] = true,
            [`WEAPON_BATTLEAXE`] = true,
            [`WEAPON_POOLCUE`] = true,
            [`WEAPON_WRENCH`] = true,
            [`WEAPON_HAMMER`] = true,
            [`WEAPON_KNUCKLE`] = true,
            [`WEAPON_STONE_HATCHET`] = true,
            [`WEAPON_TRIDENT`] = true,
            [`WEAPON_BLACKPINK`] = true,
            [`WEAPON_FANHAND`] = true,
            [`WEAPON_HAMMERTHOR`] = true,
            [`WEAPON_NOTZSAKURA`] = true,
        },
        notifyTitle = 'WEAPON LICENSE',
        notifyMessage = 'You need a weapon license to use this firearm. Get one from the Police Department.',
        notifyCooldown = 4000,
    },

    GlobalRecoilMultiplier = 1.0,

    Weapons = {
        -- Pistols --
        [1] = { hash = `WEAPON_PISTOL`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [2] = { hash = `WEAPON_PISTOL_MK2`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.15},
        [3] = { hash = `WEAPON_COMBATPISTOL`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.10},
        [4] = { hash = `WEAPON_APPISTOL`, recoil = 0.12, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [5] = { hash = `WEAPON_STUNGUN`, recoil = 0.02, rightLeftRecoil = 0.10, vehicleRecoil = 0.50, vehicleRightLeftRecoil = 0.50, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [6] = { hash = `WEAPON_PISTOL50`, recoil = 0.15, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.80},
        [7] = { hash = `WEAPON_SNSPISTOL`, recoil = 0.08, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [8] = { hash = `WEAPON_SNSPISTOL_MK2`, recoil = 0.08, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [9] = { hash = `WEAPON_HEAVYPISTOL`, recoil = 0.12, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.70},
        [10] = { hash = `WEAPON_VINTAGEPISTOL`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [11] = { hash = `WEAPON_FLAREGUN`, recoil = 0.08, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [12] = { hash = `WEAPON_MARKSMANPISTOL`, recoil = 0.16, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [13] = { hash = `WEAPON_REVOLVER`, recoil = 0.16, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [14] = { hash = `WEAPON_REVOLVER_MK2`, recoil = 0.16, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.50},
        [15] = { hash = `WEAPON_DOUBLEACTION`, recoil = 0.15, rightLeftRecoil = 0.30, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.90},
        [16] = { hash = `WEAPON_RAYPISTOL`, recoil = 0.08, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [17] = { hash = `WEAPON_CERAMICPISTOL`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.15},
        [18] = { hash = `WEAPON_NAVYREVOLVER`, recoil = 0.16, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [19] = { hash = `WEAPON_GADGETPISTOL`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.30},
        [20] = { hash = `WEAPON_TASER`, recoil = 0.02, rightLeftRecoil = 0.10, vehicleRecoil = 0.50, vehicleRightLeftRecoil = 0.50, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.00},

        -- Submachine Guns --
        [21] = { hash = `WEAPON_MICROSMG`, recoil = 0.14, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [22] = { hash = `WEAPON_SMG`, recoil = 0.13, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [23] = { hash = `WEAPON_SMG_MK2`, recoil = 0.13, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [24] = { hash = `WEAPON_ASSAULTMG`, recoil = 0.17, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.80},
        [25] = { hash = `WEAPON_COMBATPDW`, recoil = 0.11, rightLeftRecoil = 0.22, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [26] = { hash = `WEAPON_MACHINEPISTOL`, recoil = 0.13, rightLeftRecoil = 0.30, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [27] = { hash = `WEAPON_MINISMG`, recoil = 0.14, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.82, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [28] = { hash = `WEAPON_RAYCARBINE`, recoil = 0.13, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [29] = { hash = `WEAPON_ASSAULTSMG`, recoil = 0.12, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},

        -- Shotguns --
        [30] = { hash = `WEAPON_PUMPSHOTGUN`, recoil = 0.22, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [31] = { hash = `WEAPON_PUMPSHOTGUN_MK2`, recoil = 0.22, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [32] = { hash = `WEAPON_SAWNOFFSHOTGUN`, recoil = 0.25, rightLeftRecoil = 0.30, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.90},
        [33] = { hash = `WEAPON_ASSAULTSHOTGUN`, recoil = 0.16, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.50},
        [34] = { hash = `WEAPON_BULLPUPSHOTGUN`, recoil = 0.20, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.85},
        [35] = { hash = `WEAPON_MUSKET`, recoil = 0.28, rightLeftRecoil = 0.25, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [36] = { hash = `WEAPON_HEAVYSHOTGUN`, recoil = 0.20, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.85},
        [37] = { hash = `WEAPON_DBSHOTGUN`, recoil = 0.25, rightLeftRecoil = 0.30, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [38] = { hash = `WEAPON_AUTOSHOTGUN`, recoil = 0.16, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.50},
        [39] = { hash = `WEAPON_COMBATSHOTGUN`, recoil = 0.18, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.75},

        -- Assault Rifles --
        [40] = { hash = `WEAPON_ASSAULTRIFLE`, recoil = 0.15, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [41] = { hash = `WEAPON_ASSAULTRIFLE_MK2`, recoil = 0.15, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [42] = { hash = `WEAPON_CARBINERIFLE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [43] = { hash = `WEAPON_CARBINERIFLE_MK2`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [44] = { hash = `WEAPON_ADVANCEDRIFLE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.15},
        [45] = { hash = `WEAPON_SPECIALCARBINE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [46] = { hash = `WEAPON_SPECIALCARBINE_MK2`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [47] = { hash = `WEAPON_BULLPUPRIFLE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [48] = { hash = `WEAPON_BULLPUPRIFLE_MK2`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [49] = { hash = `WEAPON_COMPACTRIFLE`, recoil = 0.16, rightLeftRecoil = 0.30, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [50] = { hash = `WEAPON_MILITARYRIFLE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},

        -- Light Machine Guns --
        [51] = { hash = `WEAPON_MG`, recoil = 0.20, rightLeftRecoil = 0.34, vehicleRecoil = 0.72, vehicleRightLeftRecoil = 0.88, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [52] = { hash = `WEAPON_COMBATMG`, recoil = 0.18, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [53] = { hash = `WEAPON_COMBATMG_MK2`, recoil = 0.18, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [54] = { hash = `WEAPON_GUSENBERG`, recoil = 0.19, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},

        -- Sniper Rifles --
        [55] = { hash = `WEAPON_SNIPERRIFLE`, recoil = 0.24, rightLeftRecoil = 0.15, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [56] = { hash = `WEAPON_HEAVYSNIPER`, recoil = 0.28, rightLeftRecoil = 0.20, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.50},
        [57] = { hash = `WEAPON_HEAVYSNIPER_MK2`, recoil = 0.28, rightLeftRecoil = 0.20, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.50},
        [58] = { hash = `WEAPON_MARKSMANRIFLE`, recoil = 0.18, rightLeftRecoil = 0.15, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [59] = { hash = `WEAPON_MARKSMANRIFLE_MK2`, recoil = 0.18, rightLeftRecoil = 0.15, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},

        -- Heavy Weapons --
        [60] = { hash = `WEAPON_RPG`, recoil = 0.30, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [61] = { hash = `WEAPON_GRENADELAUNCHER`, recoil = 0.22, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [62] = { hash = `WEAPON_GRENADELAUNCHER_SMOKE`, recoil = 0.22, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.00},
        [63] = { hash = `WEAPON_MINIGUN`, recoil = 0.12, rightLeftRecoil = 0.25, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [64] = { hash = `WEAPON_FIREWORK`, recoil = 0.15, rightLeftRecoil = 0.15, vehicleRecoil = 0.50, vehicleRightLeftRecoil = 0.60, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [65] = { hash = `WEAPON_RAILGUN`, recoil = 0.25, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [66] = { hash = `WEAPON_HOMINGLAUNCHER`, recoil = 0.30, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [67] = { hash = `WEAPON_COMPACTLAUNCHER`, recoil = 0.22, rightLeftRecoil = 0.20, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.65, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [68] = { hash = `WEAPON_RAYMINIGUN`, recoil = 0.12, rightLeftRecoil = 0.25, vehicleRecoil = 0.60, vehicleRightLeftRecoil = 0.70, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [69] = { hash = `WEAPON_STICKYBOMB`, recoil = 0.00, rightLeftRecoil = 0.00, vehicleRecoil = 0.00, vehicleRightLeftRecoil = 0.00, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.00},

        -- Melee --
        [70] = { hash = `WEAPON_UNARMED`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.02},
        [71] = { hash = `WEAPON_DAGGER`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [72] = { hash = `WEAPON_BAT`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [73] = { hash = `WEAPON_BOTTLE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [74] = { hash = `WEAPON_CROWBAR`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [75] = { hash = `WEAPON_FLASHLIGHT`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [76] = { hash = `WEAPON_GOLFCLUB`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [77] = { hash = `WEAPON_HAMMER`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [78] = { hash = `WEAPON_HATCHET`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [79] = { hash = `WEAPON_KNUCKLE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [80] = { hash = `WEAPON_KNIFE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [81] = { hash = `WEAPON_MACHETE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [82] = { hash = `WEAPON_SWITCHBLADE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [83] = { hash = `WEAPON_NIGHTSTICK`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [84] = { hash = `WEAPON_WRENCH`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [85] = { hash = `WEAPON_BATTLEAXE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [86] = { hash = `WEAPON_POOLCUE`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},
        [87] = { hash = `WEAPON_STONE_HATCHET`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.15},

        -- Custom Weapons -- 
        [88] = { hash = `WEAPON_SCARH`, recoil = 0.15, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [89] = { hash = `WEAPON_M4`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [90] = { hash = `WEAPON_DEAGLE`, recoil = 0.15, rightLeftRecoil = 0.32, vehicleRecoil = 0.70, vehicleRightLeftRecoil = 0.85, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.80},
        [91] = { hash = `WEAPON_GLOCK22`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.15},
        [92] = { hash = `WEAPON_TRIDENT`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [93] = { hash = `WEAPON_BLACKPINK`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [94] = { hash = `WEAPON_FANHAND`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [95] = { hash = `WEAPON_HAMMERTHOR`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [96] = { hash = `WEAPON_NOTZSAKURA`, recoil = 0.00, vehicleRecoil = 0.00, gripMultiplier = 0.00, suppressorMultiplier = 0.00, damageMultiplier = 0.00},
        [97] = { hash = `WEAPON_AR15`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [98] = { hash = `WEAPON_HK416`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [99] = { hash = `WEAPON_TACTICALRIFLE`, recoil = 0.14, rightLeftRecoil = 0.26, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.78, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
        [100] = { hash = `WEAPON_GHC`, recoil = 0.10, rightLeftRecoil = 0.25, vehicleRecoil = 0.65, vehicleRightLeftRecoil = 0.75, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 0.80},
        [101] = { hash = `WEAPON_BSCAR`, recoil = 0.15, rightLeftRecoil = 0.28, vehicleRecoil = 0.68, vehicleRightLeftRecoil = 0.80, gripMultiplier = 0.80, suppressorMultiplier = 0.72, damageMultiplier = 1.00},
    },
}