CREATE TABLE IF NOT EXISTS `gang_car_claims` (
    `identifier` VARCHAR(60) NOT NULL,
    `gang` VARCHAR(50) DEFAULT NULL,
    `plate` VARCHAR(12) DEFAULT NULL,
    `model` VARCHAR(50) DEFAULT NULL,
    `stored` TINYINT(1) NOT NULL DEFAULT 1,
    `banned` TINYINT(1) NOT NULL DEFAULT 0,
    `claimed_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SHOW TABLES LIKE 'gang_car_claims';
